name: 'clang-format Code Formatter'
description: 'Runs clang-format on your source code so your users do not have to'
author: 'antoinealb'
inputs: 
  exclude-regex:
    description: 'A regex to exclude files or directories that should not be formatted. Default is empty.'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.exclude-regex }}
